# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 023f0cb85ae5b9bc87c0c89c31dd865fffac7d9d893869f44cef84fa856b26d6084e7d78b668e89844d02d920d308aadd702245fd8f3a87d4b5e9796af21a0a6

test:
  secret_key_base: 04c5c25b48de923514911f73d669700d2025c20932e451a95614e7037b390c85e640ac080c6046bbe41fc7b5bef28a521c9eba7e2de1614771864cd77cdf8469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
